name: CD - Daily Fetch Supabase Data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 19 * * *' # 日本時間 04:00

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Fetch data from Supabase
        run: npm run fetch
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Commit data file(s)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add data/*.json || true
          if git diff --cached --quiet; then
            echo "No data changes to commit."
          else
            git commit -m "chore(data): update study data $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push origin HEAD:main
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-data
          path: data/*.json
